- name: Add grafana repository
  yum_repository:
    name: grafana
    description: grafana yum repo
    baseurl: https://packagecloud.io/grafana/stable/el/7/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    sslverify: yes
    state: present

- name: Add influxdb repository
  yum_repository:
    name: influxdb
    description: influxdb yum repo
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
    state: present

- name: enable required repositories
  rhsm_repository: name={{ item }}
  with_items: "{{ required_repos }}"
  register: enabled_repos

- name: disable all repositories except required_repos
  rhsm_repository:
    name: "{{ item }}"
    state: disabled
  with_items: "{{ enabled_repos.repositories |
   map(attribute='id') |
   difference(required_repos) }}"

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: Install mariadb
  yum:
    name: mariadb-server
    state: latest

- name: Install grafana, influxDB and chronograf
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - grafana
    - influxdb
    - chronograf

- name: Open required ports for mariadb, grafana and influxDB
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 8086/tcp
    - 8088/tcp
    - 8888/tcp
    - 3000/tcp
    - 3306/tcp
    - 25825/tcp

- name: Reload firewalld configuration
  command: firewall-cmd --reload
  args:
    warn: no

- name: Copy the influxdb configuration file
  copy:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644

- name: Start and enable mariadb, grafana and influxDB
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
  with_items:
    - "grafana-server"
    - "influxdb"
    - "mariadb"
    - chronograf

- name: Copy the mysql schema
  copy:
    src: create.sql
    dest: /create.sql
    owner: root
    group: root
    mode: 0755

- name: Create the database and its table
  shell: /usr/bin/mysql -u root < /create.sql
  args:
    executable: /bin/bash
