- name: Configure DS3 web server instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: https://rhvm.microlab/ovirt-engine/api
    engine_user: admin@internal

    web_vm_tag: ds-web

  tasks:
    - include_vars: credentials/ovirt-credentials.yaml

    - assert:
        that:
          - engine_url is defined
          - engine_user is defined
          - engine_password is defined

    - ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"

    - name: Get Web VMs by tag
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        pattern: "tag={{ web_vm_tag }} and status = Up"
      register: web_vms

    - name: Get Web VM NICs
      ovirt_nics_facts:
        auth: "{{ ovirt_auth }}"
        vm: "{{ item }}"
      register: web_nics
      loop: "{{ web_vms.ansible_facts.ovirt_vms|json_query('[*].name') }}"

    - set_fact:
        web_ips: "{{ web_nics.results|json_query('[].ansible_facts.ovirt_nics[].reported_devices[].ips[?version==`v4`].address | []') }}"

    - name: add VMs to inventory
      add_host:
        name: "{{ item }}"
        groups: web_hosts
        ansible_ssh_user: root
      with_items: "{{ web_ips }}"

- name: Initialize web hosts
  hosts: web_hosts
  gather_facts: true
  become: true

  vars:
    web_vm_hostname_prefix: ds3-web-
    db_vm_hostname_prefix: ds3-mysql-

  tasks:

    # sets the mysql default host ds3-mysql-XXX where XXX is the number extracted from the web servers hostname following the pattern ds3-web-NNN where NNN is between 1 and 128

    - name: set mysql default host
      lineinfile:
        path: /etc/php.ini
        line: mysql.default_host = {{ db_vm_hostname_prefix }}{{ ansible_hostname | regex_replace(web_vm_hostname_prefix + '([0-9]*)', '\1') }}
        regexp: '^mysql.default_host='
        state: present

    - name: set mysql default user
      lineinfile:
        path: /etc/php.ini
        line: mysql.default_user = ds3_user
        regexp: '^mysql.default_user='
        state: present

    - name: set mysql default password
      lineinfile:
        path: /etc/php.ini
        line: mysql.default_password = ds3_password
        regexp: '^mysql.default_password='
        state: present

    - name: restart httpd service
      service: name=httpd state=restarted enabled=yes
