- name: Create DS2 DB oVirt VMs
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    how_many: 1
    engine_url: https://rhvm.poc4.maxta.com/ovirt-engine/api
    engine_user: admin@internal
    template_name: ds2-mysql-50gb-template-without-data

    db_vm_tag: ds-mysql
    db_ds2_vm_tag: ds2-mysql-50gb

    ds2_db_vm:
      name: "ds2-mysql-{{ item }}"
      tag: "{{ db_ds2_vm_tag }}"
      profile:
        state: running
        cluster: Default
        template: "{{ template_name }}"
        clone: yes
        operating_system: rhel_7x64
        placement_policy: migratable
        type: server
        memory: 8GiB
        memory_guaranteed: 8GiB
        memory_max: 8GiB
        cpu_cores: 4
        cpu_sockets: 1
        io_threads: 2
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCigf7/7tL20IMSHEYqaULiFV5A1I2lDM3kYk8RAMRhMgYDs+L3PBZoioxBgCJJTw+uSgJWfw3OOpMVKwF6ll/oK+hxB6V4NbTSsCbJID0K18bFrUWmXwzS5QU6YWtjcbRrwIo++PSUjG75UMacmDEPS+fuBDcq5JJ5miuepg8+lSZeoy16YsO2AjC8wTzWX+iTzdBk/xSOR8iQojxiMnfJ7rR1u8lO2lJEjTjGMtWqYUlr2xveZFBpQN6L7JnW8sX+At2D7nl0Mw3l//GpQiqUj6HtGO41EQ4fdM9SN8W1Mw7U23pm8Od50f8AFM9gJuVKKNcVP58X1FK1bXbQd98V root@localhost.localdomain
        graphical_console:
          protocol:
            - spice
            - vnc
        cloud_init_persist: true
        cloud_init:
          - nic_ip_address: "192.168.107.{{ item | int }}"
          - nic_gateway: 192.168.104.1
          - nic_netmask: 255.255.252.0
          - nic_on_boot: true
          - nic_name: eth0
          - nic_boot_protocol: static
          - host_name: "ds2-mysql-{{ item }}"
          - dns_search: poc4.maxta.com

  tasks:

    - include_vars: credentials/ovirt-credentials.yaml

    - assert:
        that:
          - how_many is defined
          - engine_url is defined
          - engine_user is defined
          - engine_password is defined

    - ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"

    - set_fact:
        ds2_db_vms: "{{ (ds2_db_vms | default([])) + [ds2_db_vm] }}"
      with_sequence: "start=1 count={{ how_many }}"

    - name: Create DS2 DB oVirt VMs
      include_role: name=ovirt-ansible-vm-infra
      vars:
        vms: "{{ ds2_db_vms }}"

    - name: Tag DS2 database VMs with {{ db_vm_tag }}
      ovirt_tags:
        auth: "{{ ovirt_auth }}"
        name: "{{ db_vm_tag }}"
        vms: "{{ ds2_db_vms | map(attribute='name') | list }}"
