- name: Find DB Instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    engine_url: https://rhvm.microlab/ovirt-engine/api
    engine_user: admin@internal

    db_vm_tag: ds-mysql

  tasks:
    - include_vars: credentials/ovirt-credentials.yaml

    - assert:
        that:
          - engine_url is defined
          - engine_user is defined
          - engine_password is defined

    - ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"

    - name: Get DB VMs by tag
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        pattern: "tag={{ db_vm_tag }} and status = Up"
      register: db_vms

    - name: Get DB VM NICs
      ovirt_nics_facts:
        auth: "{{ ovirt_auth }}"
        vm: "{{ item }}"
      register: db_nics
      loop: "{{ db_vms.ansible_facts.ovirt_vms|json_query('[*].name') }}"

    - set_fact:
        db_ips: "{{ db_nics.results|json_query('[].ansible_facts.ovirt_nics[].reported_devices[].ips[?version==`v4`].address | []') }}"

    - name: add DBs to inventory
      add_host:
        name: "{{ item }}"
        groups: db_hosts
        ansible_ssh_user: root
      with_items: "{{ db_ips }}"

- name: Initialize DB hosts
  hosts: db_hosts
  gather_facts: true
  become: true

  tasks:

    - block:

      - name: stop mysql service
        service: name=mariadb state=stopped

      - name: mount mysql backup on /mnt
        mount:
          path: /mnt
          fstype: xfs
          src: /dev/vdc
          opts: ro
          state: mounted

      - name: delete existing mysql directory contents
        shell: rm -rf /var/lib/mysql/*
        args:
          warn: no

      # - find:
      #     paths: /var/lib/mysql
      #     file_type: any
      #     pattern: "*"
      #   register: files_to_delete
      #
      # - name: clean mysql dir on host
      #   file: path={{ item }} state=absent
      #   with_items: "{{ files_to_delete.files }}"

      - name: start rsync job to restore database from backup
        shell: rsync -aq /mnt/ /var/lib/mysql
        async: 7200
        poll: 30

      - name: delete innodb log files
        file: path={{ item }} state=absent
        with_fileglob: /var/lib/mysql/ib_logfile*

      - name: ensure correct ownership of database directory
        file:
          path: /var/lib/mysql
          recurse: yes
          owner: mysql
          group: mysql

      - name: restore selinux label on database directory
        shell: restorecon -R /var/lib/mysql

      - firewalld:
          service: mysql
          permanent: true
          state: enabled
          permanent: yes
          immediate: yes

      - name: start and enable mysql
        service:
          name: mariadb
          state: started
          enabled: yes

      - name: create the benchmark user web
        mysql_user:
          name: web
          host: '%'
          password: web
          priv: '*.*:ALL'
          state: present

      always:

      - mount:
          path: /mnt
          state: absent
